### ISSUE TITLE
Vertaisarviointi #1

### ISSUE THREAD

**Issue by ptuomola** [ethanrailo/urheilutapahtumat#3]
Ylipäätään näyttää hyvältä, koodin rakenne on selkeää, ja toiminnallisuuskin on jo aika pitkällä. Hienoa työtä!

Muutamia asioita joita voisi ehkä miettiä:

**Käyttäjäkokemus**

- Paikan lisäyksessä kannattaisi varmaan tarkastaa myös nimen perusteella, onko tälläinen paikka jo tietokannassa. Tällä hetkellähän tarkastus on koordinaattien perusteella - mutta koordinaatithan voivat olla helposti hieman eri, vaikka samasta paikasta onkin kysymys (esim. mittauspaikan tai pyöristysvirheen takia). 

- Hyvä lisätoiminto olisi, jos järjestelmään lisätyt paikkakunnat / lajit tulisivat automaattisesti näkyviin myös valikoihin. Tällä hetkellähän ne varmaan olisi tulossa "Muut"-valinnan alle

**Koodin katselmointi**

- Lomakkeiden hallintaan voisi käyttää myös WTFormsia - tämän avulla saisi input validoinnin hoidettua WTFormsin kautta, eikä siihen tarvittaisi erillisiä validate_xxx() funktioita. Toisaalta tietysti laittamalla validoinnit noihin add()-metodeihin niitä voi käyttää koodissa myös muissakin paikoissa kuin lomakkeesta käsin...

- Sen sijaan että kaikki kontrollerit koodataan yhteen routes.py:hyn, tämän voisi jakaa eri moduleihin Flaskin Blueprints-konseptia käyttäen - tekisi koodista modulaarisempaa.

- APIn URL:t voisi ehkä nimetä vähän REST-konvention mukaisemmin, eli esim. GET /venues/get_all olisi GET /venues, POST /venues/add olisi vain POST /venues, samoin /events/new olisi /events yms. 

Mutta muuten en kyllä keksi paljoakaan parannettavaa - hyvältä näyttää!

**Comment by ethanrailo** [comment]
Moi, kiitos erittäin hyvästä vertaisarviosta! Koodin puolelta näkyy varmasti se, että Python on minulle varsin vieras vielä web-sovelluskehityksessä ja tulee tehtyä asioita turhan pitkästä tavarasta ja hieman ei-modulaarisesti :-) Otan ehdottomasti kommenttisi huomioon ja pyrin refaktoroimaan suurimpia häröjä, kun saan ominaisuudet pultattua kasaan loppujen juttujen osalta.
